### ISSUE TITLE
Qemu CPU usage is too much

### ISSUE THREAD

**Issue by milisarge** [nuta/resea#11]
I tested with qemu, approximately it uses %25 of CPU. i played with `counts_per_tick` value but didn't have any stable state.

**Comment by milisarge** [comment]
i did some tests with new kernel config about time slice, and i didn't see any less CPU usage significantly. here is my values and percents
```
200 %20-%25
150  %25-%30
100  %25-%30
50   %27-%30
25   %25-%28
10   %26-%29
```

**Comment by nuta** [comment]
Thanks for the report! I'll try to figure out the root cause.

**Comment by nuta** [comment]
Feel free to reopen if it still occur.
