### ISSUE TITLE
make menuconfig fails

### ISSUE THREAD

**Issue by chtcheglov-ilia** [nuta/resea#3]
`make menuconfig` fails with

> CONFIG  .config.mk
> Traceback (most recent call last):
>   File "./tools/config.py", line 3, in <module>
>     import defconfig
> ModuleNotFoundError: No module named 'defconfig'
> Traceback (most recent call last):
>   File "./tools/config.py", line 3, in <module>
>     import defconfig
> ModuleNotFoundError: No module named 'defconfig'
> Makefile:101: recipe for target 'menuconfig' failed
> make: *** [menuconfig] Error 1

**Comment by chtcheglov-ilia** [comment]
The documentation didn't say I have to run `pip3 install kconfiglib`

**Comment by nuta** [comment]
Thank you for letting me know! I'll add it to the documentation.
